### ISSUE TITLE
Change copyright statement.

### ISSUE THREAD

**Issue by vphill** [unt-libraries/untl-metadata-documentation#5]
Instead of "© Copyright 2022, UNT Libraries." at the bottom of pages - https://library.unt.edu/metadata/fields/creator.html

Can we make this say. 

© Copyright 2022, University of North Texas. This work is licensed under [Creative Commons Attribution 4.0 International](https://creativecommons.org/licenses/by/4.0/)

**Comment by jason-ellis** [comment]
This is done  in commit 46110d2 and deployed to production. I had to override the theme's footer template in `docs/_templates/footer.html`, which actually gives us a lot of flexibility. Let me know if you need me to make any further tweaks.

![image](https://user-images.githubusercontent.com/6383540/229613076-590770b1-69eb-49bd-b63c-1dbd0a153add.png)
